name: qe-mini
channels:
  - default
  - conda-forge
dependencies:
  - python=3.7.*
  - pip
  - pandas
  - matplotlib
  - pip:
    - quantecon
    - jupyter-cache[jupyter-book]
    - git+https://github.com/ExecutableBookProject/jupyter-book